# wrangler.toml
name = "earthquake"
compatibility_date = "2024-06-05" # Feel free to update to a more recent date

# Configuration for Cloudflare Worker
main = "functions/[[catchall]].js"
workers_dev = true

kv_namespaces = [
  { binding = "CLUSTER_KV", id = "2e7c7b5faf2f47868a048bd8043edebc", preview_id = "25424bdebf90459ea61121e9b3dfc4ee" }
]

[site]
bucket = "./dist"

# KV Namespace binding for cluster definitions
# -----------------------------------------------------------------------------------------
# IMPORTANT INSTRUCTIONS FOR THE USER:
# 1. Create KV Namespaces:
#    You need to create KV namespaces using the Wrangler CLI. It's recommended to have
#    separate namespaces for production and preview/local development.
#    Run these commands in your terminal:
#      wrangler kv:namespace create CLUSTER_KV
#      wrangler kv namespace create CLUSTER_KV_PREVIEW
#
# 2. Update IDs Below:
#    Wrangler will output an 'id' for each namespace created.
#    Replace "REPLACE_WITH_PRODUCTION_KV_ID" with the ID for CLUSTER_KV.
#    Replace "REPLACE_WITH_PREVIEW_KV_ID" with the ID for CLUSTER_KV_PREVIEW.
#
# 3. Dashboard Configuration (Crucial for Git-integrated Pages):
#    For projects deployed via Git, bindings set in the
#    Cloudflare Dashboard (Settings -> Functions -> KV Namespace Bindings) often take
#    precedence for deployed environments (production and preview).
#    Ensure you also configure the 'CLUSTER_KV' binding there, pointing it to the
#    respective KV namespaces for your production and preview environments.
#    This wrangler.toml configuration is especially useful for local development
#    with `wrangler dev`.
# -----------------------------------------------------------------------------------------


# Example of other potential configurations (uncomment and adjust if needed):
# [vars]
# MY_VARIABLE = "production_value"
#
# [env.preview.vars]
# MY_VARIABLE = "preview_value"
#

# This explicitly tells 'wrangler dev' to use the preview_id for CLUSTER_KV.
[env.dev.kv_namespaces]
CLUSTER_KV = { preview_id = "25424bdebf90459ea61121e9b3dfc4ee" }

# D1 Database binding for primary data
# -----------------------------------------------------------------------------------------
# IMPORTANT INSTRUCTIONS FOR THE USER:
# 1. Create D1 Database:
#    You need to create a D1 database using the Wrangler CLI.
#    Run this command in your terminal:
#      wrangler d1 create PrimaryDB
#
# 2. Update IDs Below:
#    Wrangler will output a 'database_id' for the created D1 database.
#    Replace "REPLACE_WITH_PRODUCTION_D1_ID" with this ID for your production database.
#    It is also recommended to create a separate D1 database for preview/local development
#    and update "REPLACE_WITH_PREVIEW_D1_ID" accordingly. You can run:
#      wrangler d1 create PrimaryDB-preview
#    Then use its ID for 'preview_database_id'.
#
# 3. Dashboard Configuration (Crucial for Git-integrated Pages):
#    For projects deployed via Git, D1 bindings configured in the
#    Cloudflare Dashboard (Settings -> Functions -> D1 Database Bindings) often take
#    precedence for deployed environments (production and preview).
#    Ensure you also configure the 'DB' binding there, pointing it to the
#    respective D1 databases for your production and preview environments.
#    This wrangler.toml configuration is especially useful for local development
#    with `wrangler dev`.
# -----------------------------------------------------------------------------------------
[[d1_databases]]
binding = "DB" # Binding name used in your Worker code
database_name = "PrimaryDB" # Name of the D1 database (used in wrangler d1 commands)
database_id = "8a0a26e9-ba3c-4984-9023-c1803f611a05"
preview_database_id = "57ba069c-5763-41c3-965d-0df87b0ef26b" # For `wrangler dev --preview` or previews

# This explicitly tells 'wrangler dev' (local development) to use the preview_database_id for DB.
# Make sure 'REPLACE_WITH_PREVIEW_D1_ID' here matches the preview_database_id above,
# or a specific local/dev D1 instance ID if you have one.
[env.dev.d1_databases]
DB = { preview_database_id = "57ba069c-5763-41c3-965d-0df87b0ef26b" }

[triggers]
crons = ["*/1 * * * *"] # Run every minute

# If you have other bindings (like R2, Services), define them here too.
# Refer to Cloudflare Wrangler documentation for more details.
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true