// src/pages/learn/TsunamisPage.jsx
import React from 'react';
import SeoMetadata from '../../components/SeoMetadata';
import { Link } from 'react-router-dom';

const TsunamisPage = () => {
  return (
    <>
      <SeoMetadata
        title="Tsunamis and Earthquakes | Seismic Science"
        description="Learn how undersea earthquakes can generate devastating tsunamis, understand the warning signs, and know the safety procedures to follow."
        keywords="tsunamis, earthquakes, tsunami safety, undersea earthquakes, subduction zones, tsunami warnings"
        pageUrl="https://earthquakeslive.com/learn/tsunamis-and-earthquakes"
        canonicalUrl="https://earthquakeslive.com/learn/tsunamis-and-earthquakes"
        locale="en_US"
        type="article"
      />
      <div className="p-3 md:p-4 space-y-4 text-slate-200 max-w-3xl mx-auto">
        <h1 className="text-lg font-semibold text-indigo-400 sticky top-0 bg-slate-900 py-2 z-10 -mx-3 px-3 sm:-mx-4 sm:px-4 border-b border-slate-700">
          Tsunamis and Earthquakes
        </h1>

        <div className="prose prose-invert prose-sm sm:prose-base max-w-none">
          <p>
            A tsunami is a series of ocean waves with very long wavelengths (typically hundreds of kilometers) caused by large-scale disturbances of the ocean. The most common cause of tsunamis is a large, undersea earthquake at a tectonic plate boundary.
          </p>

          <h2 className="text-indigo-300">How Do Earthquakes Generate Tsunamis?</h2>
          <p>
            Tsunamis are most often generated by earthquakes that occur in subduction zones, areas where an oceanic plate is being forced down into the mantle by a continental plate. The process unfolds as follows:
          </p>
          <ol>
            <li><strong>Stress Accumulation:</strong> As the oceanic plate subducts, the overlying plate gets stuck and distorted, slowly building up stress.</li>
            <li><strong>Sudden Rupture (The Earthquake):</strong> Eventually, the stress overcomes the friction between the plates. The overriding plate snaps back into position, an event we experience as a major earthquake.</li>
            <li><strong>Water Displacement:</strong> This sudden uplift of the seafloor displaces a massive volume of water above it, pushing it up from the normal sea level.</li>
            <li><strong>Wave Formation:</strong> Gravity pulls this displaced water back down, and the energy from this movement creates powerful waves that spread outward in all directions – a tsunami.</li>
          </ol>
          <p>
            For an earthquake to generate a significant tsunami, it typically needs to be a shallow-focus earthquake with a magnitude of at least 7.5.
          </p>

          <h2 className="text-indigo-300">Characteristics of a Tsunami</h2>
          <ul>
            <li><strong>Speed:</strong> In the deep ocean, tsunami waves can travel as fast as a jet plane (over 800 km/h or 500 mph).</li>
            <li><strong>Wave Height:</strong> In deep water, the wave height might be less than a meter and is often unnoticeable. As the wave approaches shallow coastal waters, its speed decreases and its height increases dramatically.</li>
            <li><strong>Wave Period:</strong> Unlike normal ocean waves, the period between tsunami wave crests can be from minutes to hours long. The first wave is often not the largest.</li>
          </ul>

          <h2 className="text-indigo-300">Tsunami Warning Signs</h2>
          <p>If you are in a coastal area, know these natural warning signs:</p>
          <ul>
            <li>A strong earthquake that makes it hard to stand.</li>
            <li>A loud, roaring sound coming from the ocean.</li>
            <li>A sudden and unusual rise or fall in sea level (the water may recede far from the coast, exposing the ocean floor).</li>
          </ul>
          <p>
            Official warnings are also issued by Tsunami Warning Centers. These are based on seismic data and sea-level measurements from a network of buoys.
          </p>

          <h2 className="text-indigo-300">Safety and Preparedness</h2>
          <p>
            If you receive a tsunami warning or observe any of the natural warning signs, take immediate action:
          </p>
          <ul>
            <li><strong>Move Inland:</strong> Move as far inland as possible, away from the coast.</li>
            <li><strong>Seek Higher Ground:</strong> If you cannot move inland, seek higher ground (at least 30 meters or 100 feet above sea level).</li>
            <li><strong>Stay Put:</strong> Once you are in a safe location, stay there. The danger can last for hours as subsequent waves arrive.</li>
            <li><strong>Listen to Officials:</strong> Follow the instructions of local emergency officials.</li>
          </ul>

          <p className="mt-6">
            To explore related topics, you can return to the main <Link to="/learn" className="text-indigo-400 hover:underline">Learn Page</Link>.
          </p>
        </div>
      </div>
    </>
  );
};

export default TsunamisPage;
