-- Migration 0006: Trigger for ClusterDefinitions.updatedAt
-- This trigger (trg_ClusterDefinitions_AutoUpdate_UpdatedAt) was applied manually
-- using `wrangler d1 execute` on the deployed D1 environment due to issues
-- with applying it via a migration file.
--
-- The SQL executed directly was:
-- DROP TRIGGER IF EXISTS trg_ClusterDefinitions_AutoUpdate_UpdatedAt;
-- CREATE TRIGGER trg_ClusterDefinitions_AutoUpdate_UpdatedAt
-- AFTER UPDATE ON ClusterDefinitions
-- FOR EACH ROW
-- BEGIN
--     UPDATE ClusterDefinitions SET updatedAt = STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW') WHERE clusterId = OLD.clusterId;
-- END;
